### ISSUE TITLE
restructure moves photos inside of album?

### ISSUE THREAD

**Issue by DavyLandman** [MrYakobo/exif-wrapper#1]
Great script, I was reading the source and noticed this line:

https://github.com/MrYakobo/exif-wrapper/blob/81745de0b00c87793f0884ad8d8f4f2a4c52ed75/fix_metadata.py#L104

Wouldn't that also move the photo's directory under albums?

**Comment by MrYakobo** [comment]
The line at 101 moves any Photos from $YEAR to Photos. So the second glob won't match those. But yeah this is garbage code. Like all code I write and later come back to look at😉

The next time I'm sitting with this codebase I'll try harder to design something before coding... 👍

**Comment by DavyLandman** [comment]
I actually had to patch the code to work around this. that second glob matches `f"{rootdir}/Photos` as well right? the one that was moved to before.

**Comment by MrYakobo** [comment]
I'm not sure what you mean @DavyLandman

If you think your improvements can help others, open a PR and I'll have a look

**Comment by DavyLandman** [comment]
On my machine the following happened:

input:

```
TAKEOUT/Photos from 2023/..
TAKEOUT/Album 1/..
```

then this is run:

```
   _restructure_if_needed(f"{rootdir}/Photos from */", f"{rootdir}/Photos")
```

which makes

```
TAKEOUT/Photos/Photos from 2023/..
TAKEOUT/Album 1/..
```

so then 

```
    _restructure_if_needed(f"{rootdir}/*/", f"{rootdir}/Albums")
```

also moves `/Photos/` into `/Albums`:

```
TAKEOUT/Albums/Photos/Photos from 2023/..
TAKEOUT/Albums/Album 1/..
```

Since `rootdir/*` matches `rootdir/Photos`. That's my bug report. I don't have enough experience to change that in the python way.

**Comment by MrYakobo** [comment]
I see your point now. It's fixed in the latest commit on main now. Thank you for the bug report

https://github.com/MrYakobo/exif-wrapper/commit/f9916d1c8677ea6144c57ea4a13a528394eac07a
