### ISSUE TITLE
IndexError: index out of range 

### ISSUE THREAD

**Issue by OlegLoewen** [MrYakobo/exif-wrapper#3]
Hello,
I get the following error, while after running 'docker-compose up' the very first time:
```IndexError: list index out of range

Traceback (most recent call last):

  File "/app/fix_metadata.py", line 125, in <module>

    main(args.rootdir)

  File "/app/fix_metadata.py", line 115, in main

    rootdir = glob(f"{rootdir}/Google*/")[0].rstrip('/')

              ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^

IndexError: list index out of range```

**Comment by MrYakobo** [comment]
hey there,
this repo should be treated as abadonware. I recently got kids and don't have the time to support and debug this. I'm sorry.

However, lukehmcc forked this project and has been helpful to others, try using his repo instead :+1:

https://github.com/lukehmcc/exif-wrapper
